version: '3.8'
services:
  app:
    build: .
    expose:
      - '3000'
    volumes:
      - static_content:/app/frontend/dist
    environment:
      - MONGO_URI=mongodb://mongo:27017/arilovip
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_content:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  mongo-data:
  static_content:
